{
    "event_type": "instance.volume_attach.error",
    "payload": {
        "$ref": "common_payloads/InstanceActionVolumePayload.json#",
        "nova_object.data": {
            "fault": {
                "nova_object.data": {
                    "exception": "CinderConnectionFailed",
                    "exception_message": "Connection to cinder host failed: Connection timed out",
                    "function_name": "attach_volume",
                    "module_name": "nova.tests.functional.notification_sample_tests.test_instance",
                    "traceback": "Traceback (most recent call last):\n  File \"nova/compute/manager.py\", line ..."
                },
                "nova_object.name": "ExceptionPayload",
                "nova_object.namespace": "nova",
                "nova_object.version": "1.1"
            }
        }
    },
    "priority": "ERROR",
    "publisher_id": "nova-compute:compute"
}
